In [6]:
import pandas as pd
import numpy as np

df_rf = pd.read_csv("data/DTB3.csv")

# rename for clarity
df_rf = df_rf.rename(columns={
    "observation_date": "date",
    "DTB3": "yield"
})

# convert date
df_rf['date'] = pd.to_datetime(df_rf['date'])

In [7]:
display(df_rf)

           date  yield
0    2010-01-04   0.08
1    2010-01-05   0.07
2    2010-01-06   0.06
3    2010-01-07   0.05
4    2010-01-08   0.05
...         ...    ...
4167 2025-12-24   3.60
4168 2025-12-25    NaN
4169 2025-12-26   3.56
4170 2025-12-29   3.57
4171 2025-12-30   3.55

[4172 rows x 2 columns]

In [8]:
# forward fill to not have NaN

df_rf['yield'] = pd.to_numeric(df_rf['yield'], errors='coerce')
df_rf['yield'] = df_rf['yield'].ffill()

In [9]:
display(df_rf)

           date  yield
0    2010-01-04   0.08
1    2010-01-05   0.07
2    2010-01-06   0.06
3    2010-01-07   0.05
4    2010-01-08   0.05
...         ...    ...
4167 2025-12-24   3.60
4168 2025-12-25   3.60
4169 2025-12-26   3.56
4170 2025-12-29   3.57
4171 2025-12-30   3.55

[4172 rows x 2 columns]

In [ ]:
# check the number of recorde per year for 3M t-bills

counts = df_rf.groupby(df_rf['date'].dt.year).size()
print(counts)

date
2010    260
2011    260
2012    261
2013    261
2014    261
2015    261
2016    261
2017    260
2018    261
2019    261
2020    262
2021    261
2022    260
2023    260
2024    262
2025    260
dtype: int64

In [ ]:
# check the same for SP500

In [10]:
# convert yield (%) -> daily return
df_rf['rf_daily'] = (1 + df_rf['yield']/100)**(1/252) - 1

In [11]:
display(df_rf)

           date  yield  rf_daily
0    2010-01-04   0.08  0.000003
1    2010-01-05   0.07  0.000003
2    2010-01-06   0.06  0.000002
3    2010-01-07   0.05  0.000002
4    2010-01-08   0.05  0.000002
...         ...    ...       ...
4167 2025-12-24   3.60  0.000140
4168 2025-12-25   3.60  0.000140
4169 2025-12-26   3.56  0.000139
4170 2025-12-29   3.57  0.000139
4171 2025-12-30   3.55  0.000138

[4172 rows x 3 columns]